### ISSUE TITLE
Whitespace in JSON 

### ISSUE THREAD

**Issue by xbln** [corona-warn-app/cwa-quicktest-onboarding#29]
In https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/Anbindung-der-Partnersysteme-ohne-DCC
you write:
`Input für das Base64 Encoding (Leerzeichen beachten!):`
Question:
Is it true that despite of RFC8259 (where whitespaces between and around objects will be ignored) whitespaces are mandatory?

**Comment by maryisdead** [comment]
I'm using PHP's `json_encode` and it works fine. At least for pseudonymised tests. So I guess they don't really care.

Psersonalised tests don't work at all for me. ¯\_(ツ)_/¯

**Comment by xbln** [comment]
Tx Maryisdead, but if they diverge from RFC I have to make allowances for a bundle of usecases. It would be nice if they just state, if they follow RFC or not.

**Comment by maryisdead** [comment]
I agree completely. It's an absolutely confusing hint and they don't even seem to follow through with it.

Also, in pretty much every language that rule would basically force you to roll your own JSON library or worse, construct the JSON from string concatenation.

Anyways, as I said, "regular" JSON works and our integration is live and running fine since a week now.

**Comment by MartinKonrad** [comment]
The hint concerning the whitespaces is no longer valid. I've deleted it from the documentation. The implementation is RFC8259 compliant. Sorry for confusion.
